openapi: 3.0.0
info:
  title: Vilten JWT Auth
  description: Vilten JWT Auth authorization API in swagger [www.vil10.com](http://www.vil10.com/).
  version: 0.1.0

servers:
  - url: http://localhost:10001/v1
    description: Servers are in progress
  - url: http://auth.vil10.com/v1
    description: Servers are in progress

paths:
  /server/info:
    get:
      summary: Returns an information JSON.
      description: Returns an information about API, version, name, developer, etc.
      operationId: server/getServerInfo
      responses:
        '200':
          description: A JSON with information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerInfo'
components:
  schemas:
    ServerInfo:
      type: object
      properties:
        version:
          type: string
        name:
          type: string
        description:
          type: string
        developedBy:
          type: string
    